server:
  port: 8080
  servlet:
    context-path: /login

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.10.143:3306/miner_ue?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT
    username: root
    password: Cdsf@119
    # devtool热部署
  debug: true
  spring:
    devtools:
      restart:
        enabled: true  #开启热部署
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效

#国际化配置文件目录
  messages:
    basename: i18n/international
#配置Mapper.xml映射文件
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
#  #thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    enabled: true
    cache: false