server:
  port: 8081

spring:
  ################## mysql-config ################
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.10.143:3306/miner_ue?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: Cdsf@119
  ################## jpa-config ################
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
